version: "3.2"
services:
  mongo:
    image: mongo
    volumes:
      - ./mongodb:/data/db
    ports:
      - "127.0.0.1:31500:27017"
    network_mode: bridge

  mongoexpress:
    image: mongo-express
    ports:
      - "127.0.0.1:31000:8081"
    links:
      - mongo
    network_mode: bridge

  rabbit:
    image: byteflair/rabbitmq-stomp
    ports:
      - "127.0.0.1:14000:15672"
      - "127.0.0.1:13000:15674"
    network_mode: bridge

  node:
    image: "node:latest"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    environment:
      - MONGO_ADDR=mongo
      - RABBIT_ADDR=rabbit
    links:
      - mongo
      - rabbit
    command: "npm start"
    restart: "on-failure"
    network_mode: bridge
