version: "3.2"
services:
  mongo:
    image: mongo
    volumes:
      - ./mongodb-dev:/data/db

  mongoexpress:
    image: mongo-express
    ports:
      - target: 8081
        published: 32000
        mode: host
    depends_on:
      - mongo

  rabbit:
    image: byteflair/rabbitmq-stomp
    ports:
      - target: 15672
        published: 24000
        mode: host
      - target: 15674
        published: 23000
        mode: host

  node:
    image: "node:latest"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    environment:
      - MONGO_ADDR=mongo
      - RABBIT_ADDR=rabbit
    depends_on:
      - mongo
      - rabbit
    command: "npm start"
