version: "2"
services:
  mongo:
    image: mongo
    network_mode: bridge
    volumes:
      - ./mongodb:/data/db

  mongoexpress:
    image: mongo-express
    ports:
      - "31000:8081"
    links:
      - mongo
    restart: on-failure
    network_mode: bridge

  rabbit:
    image: byteflair/rabbitmq-stomp
    ports:
      - "14000:15672"
      - "13000:15674"
    network_mode: bridge

  node:
    image: "node:latest"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    links:
      - mongo
      - rabbit
    command: "npm start"
    restart: on-failure
    network_mode: bridge
