version: "3.2"
services:
  mongo-dev:
    image: mongo
    volumes:
      - ./mongodb-dev:/data/db
    ports:
      - "127.0.0.1:32500:27017"
    network_mode: bridge

  mongoexpress-dev:
    image: mongo-express
    ports:
      - "127.0.0.1:32000:8081"
    links:
      - mongo-dev
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-dev
    network_mode: bridge

  rabbit-dev:
    image: byteflair/rabbitmq-stomp
    ports:
      - "127.0.0.1:24000:15674"
      - "127.0.0.1:25000:15672"
    network_mode: bridge

  node-dev:
    image: "node:latest"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    environment:
      - MONGO_ADDR=mongo-dev
      - RABBIT_ADDR=rabbit-dev
    links:
      - mongo-dev
      - rabbit-dev
    command: "npm start"
    restart: "on-failure"
    network_mode: bridge
